name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  app-ci:
    name: App Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
          cd app
          yarn install

      - name: Test
        run: |
          cd app
          yarn test

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1

  api-ci:
    name: API Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Static Code Analysis
        run: |
          make lint
          make type-check

      - name: Unit Test
        run: make test-unit

      - name: E2E Tests
        run: make test-e2e

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1
